from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MessageMetadata:
    """Provenance and dataset metadata for a single ChatMessage.

    All fields are optional and default to None / True so callers that
    only care about tone_meta (the existing field) can ignore this entirely.

    speaker_source values (non-exhaustive):
      "human_local"          — Alex, physically present at the device
      "sity_local"           — Sity, generated by the backend
      "synthetic_claude_user" — prompt generated by Claude for dataset purposes
      "human_guest"          — future: a human other than Alex
      "future_voice"         — future: speaker identified via voice
      "future_face"          — future: speaker identified via camera
      "unknown"              — could not determine

    dataset_source values:
      "normal_use"            — organic conversation
      "synthetic_claude_user" — generated by the Claude dataset generator
      "human_guest"           — guest conversation
      "debug_test"            — debugging / test traffic, not for training
    """

    speaker_id: str | None = None
    speaker_label: str | None = None
    speaker_source: str | None = None
    speaker_confidence: float | None = None
    identity_evidence_json: str | None = None
    dataset_source: str | None = None
    dataset_eligible: bool = True
    dataset_tags_json: str | None = None


def build_message_metadata(
    *,
    role: str = "user",
    speaker_source: str | None = None,
    dataset_source: str = "normal_use",
    dataset_eligible: bool = True,
    dataset_tags_json: str | None = None,
    speaker_id: str | None = None,
    speaker_label: str | None = None,
    speaker_confidence: float | None = None,
    identity_evidence_json: str | None = None,
) -> MessageMetadata:
    """Return MessageMetadata with sensible defaults for a normal conversation turn.

    If speaker_source is not provided:
    - role="sity"  → "sity_local"
    - anything else → "human_local"
    """
    if speaker_source is None:
        speaker_source = "sity_local" if role == "sity" else "human_local"
    return MessageMetadata(
        speaker_id=speaker_id,
        speaker_label=speaker_label,
        speaker_source=speaker_source,
        speaker_confidence=speaker_confidence,
        identity_evidence_json=identity_evidence_json,
        dataset_source=dataset_source,
        dataset_eligible=dataset_eligible,
        dataset_tags_json=dataset_tags_json,
    )
